import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather Painel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex min-h-screen">
        <Sidebar />

        <div id="main" className="flex-1 p-10 bg-gray-100 ml-20">
          <div className="max-w-screen-md text-xl space-y-3">
            <h1 className="text-2xl">Olá, pessoal! 👋🏼</h1>
            <p>
              Esté é o meu projeto de transdutores da disciplina{' '}
              <strong>EEL7013</strong>, meu objetivo com ele é conectar os meus
              conhecimentos de eletrônica com os meus conhecimentos de
              desenvolvimento de software.
            </p>
            <h2>Conhecimentos obtidos:</h2>
            <ul className="ml-4">
              <li>- C++;</li>
              <li>- Javascript;</li>
              <li>- Python;</li>
              <li>- Funcionamento de microprocessadores e sensores;</li>
              <li>- Princípios de Sistemas Embarcados;</li>
              <li>- Conexão de microprocessador via VPS;</li>
              <li>- Internet of things (IoT), MQTT Protocol;</li>
              <li>- API;</li>
            </ul>
            <p>
              Agradecimentos à Profª Dr. Eng. Daniela Suzuki e ao Eng. Níkola
              Zaia.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
