import Head from 'next/head'
import Image from 'next/image'
// import { HomeIcon } from '@heroicons/react/outline'
import { ChartBarIcon, HomeIcon } from '@heroicons/react/solid'
import Link from 'next/link'

export default function Home() {
  const menuOptions = [
    {
      name: 'Home',
      icon: HomeIcon
    },
    {
      name: 'Stats',
      icon: ChartBarIcon
    }
  ]

  return (
    <div className="relative">
      <Head>
        <title>Wheater</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50 h-screen w-24 flex-col absolute inset-y-0 left-0 -translate-x-full transition">
        <div id="logo" className="flex justify-center ">
          <img
            className="p-2 h-24 grayscale"
            src="https://portalpadrao.ufma.br/ineof/imagens/logo-ufsc.png/@@images/84622670-9bb9-4fee-9460-dcfd76b7e33f.png"
          />
        </div>
        <div className="">
          {menuOptions.map(item => (
            <div className="block hover:bg-white rounded-r-md hover:border-r-4 border-blue-500 p-2 hover:font-medium transition-colors ease-in duration-300 cursor-pointer">
              <div className="flex justify-center">
                <item.icon className="h-6 text-blue-500" />
              </div>
              <div className="flex justify-center text-sm">
                <Link href="#">{item.name}</Link>
              </div>
            </div>
          ))}
        </div>
      </div>
      <main className="ml-24 h-screen py-24">
        <div className="container mx-auto bg-gray-200">oi</div>
      </main>

      <footer className=""></footer>
    </div>
  )
}
