import Head from 'next/head'
import Image from 'next/image'
// import { HomeIcon } from '@heroicons/react/outline'
import { ChartBarIcon, HomeIcon } from '@heroicons/react/solid'
import Link from 'next/link'
import Graph from '../components/Graph'
import axios from 'axios'
import { useState, useEffect } from 'react'

export default function Home() {
  const menuOptions = [
    {
      name: 'Home',
      icon: HomeIcon
    },
    {
      name: 'Stats',
      icon: ChartBarIcon
    }
  ]

  const apikey = 'f4d949bfa64fbe2c8bf7ecbb7a7b3154'

  const [weather, setWeather] = useState({})
  const [loadingWeather, setLoadingWeather] = useState(false)

  useEffect(() => {
    async function getWeatherByLocation(city) {
      const resp = await fetch(
        `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apikey}`
      )

      const data = await resp.json()

      setWeather(data)
      setLoadingWeather(true)
    }

    getWeatherByLocation('Florianopolis')
  }, [])

  console.log(weather)

  return (
    <div>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex min-h-screen">
        <div className="bg-gray-50 w-24">
          <div id="logo" className="flex justify-center ">
            <img
              className="p-2 h-24 grayscale"
              src="https://portalpadrao.ufma.br/ineof/imagens/logo-ufsc.png/@@images/84622670-9bb9-4fee-9460-dcfd76b7e33f.png"
            />
          </div>
          <nav>
            {menuOptions.map(item => (
              <div className="block hover:bg-white rounded-r-md hover:border-r-4 border-blue-500 p-2 hover:font-medium transition-colors ease-in duration-300 cursor-pointer">
                <div className="flex justify-center">
                  <item.icon className="h-6 text-blue-500" />
                </div>
                <div className="flex justify-center text-sm">
                  <Link href="#" key={item.name}>
                    {item.name}
                  </Link>
                </div>
              </div>
            ))}
          </nav>
        </div>
        <div id="main" className="flex-1 p-10 bg-gray-100">
          <div className="flex mb-5 space-x-5">
            <div className="shadow-xl rounded-xl bg-white w-1/2">
              <div className="pt-5 px-5 text-2xl font-medium ">Temperature</div>
              <div className="px-5 text-md text-gray-500">
                degrees Celsius (°C)
              </div>
              <div className="flex justify-center">
                {loadingWeather ? (
                  <div className="text-5xl pb-5">
                    {(weather.main.temp - 273.15).toFixed(2)}°C
                  </div>
                ) : (
                  <img
                    className="h-6 w-6 mb-5"
                    src="https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif"
                  />
                )}
              </div>
            </div>
            <div className="shadow-xl rounded-xl bg-white w-1/2">oi</div>
          </div>
          <div className="shadow-xl rounded-xl bg-white">
            <div className="pt-5 px-5 text-2xl font-medium ">
              Temperature ESP
            </div>
            <div className="pb-5 px-5 text-md text-gray-500">
              degrees Celsius (°C)
            </div>
            <div className="flex justify-center">
              <Graph />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
