import Head from 'next/head'
import Image from 'next/image'

import { useState, useEffect } from 'react'
import GraphT from '../components/GraphT'
import GraphH from '../components/GraphH'
import Sidebar from '../components/Sidebar'

export default function Home() {
  const apikey = 'f4d949bfa64fbe2c8bf7ecbb7a7b3154'

  const [weather, setWeather] = useState({})
  const [loadingWeather, setLoadingWeather] = useState(false)

  useEffect(() => {
    async function getWeatherByLocation(city) {
      const resp = await fetch(
        `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apikey}`
      )

      const data = await resp.json()

      setWeather(data)
      setLoadingWeather(true)
    }

    getWeatherByLocation('Florianopolis')
  }, [])

  return (
    <div>
      <Head>
        <title>Weather Painel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex min-h-screen">
        <Sidebar />

        <div id="main" className="flex-1 p-10 bg-gray-100 ml-20">
          <div className="flex mb-5 space-x-5">
            <div className="shadow-xl rounded-xl bg-white w-full">
              <div className="pt-5 px-5 text-2xl font-medium ">Temperature</div>
              <div className="px-5 text-md text-gray-500">
                degrees Celsius (°C)
              </div>
              <div className="flex justify-center">
                {loadingWeather ? (
                  <div className="text-5xl pb-5">
                    {(weather.main.temp - 273.15).toFixed(0)}°C
                  </div>
                ) : (
                  <img
                    className="h-6 w-6 mb-5"
                    src="https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif"
                  />
                )}
              </div>
            </div>
            <div className="shadow-xl rounded-xl bg-white w-full">
              <div className="pt-5 px-5 text-2xl font-medium ">Humidity</div>
              <div className="px-5 text-md text-gray-500">Percentage (%)</div>
              <div className="flex justify-center">
                {loadingWeather ? (
                  <div className="text-5xl pb-5">{weather.main.humidity}%</div>
                ) : (
                  <img
                    className="h-6 w-6 mb-5"
                    src="https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif"
                  />
                )}
              </div>
            </div>
          </div>
          <div className="shadow-xl rounded-xl bg-white mb-5">
            <div className="pt-5 px-5 text-2xl font-medium ">
              Temperature ESP
            </div>
            <div className="pb-5 px-5 text-md text-gray-500">
              degrees Celsius (°C)
            </div>
            <div className="flex justify-center h-1/2">
              <GraphT />
            </div>
          </div>
          <div className="shadow-xl rounded-xl bg-white">
            <div className="pt-5 px-5 text-2xl font-medium ">Humidity ESP</div>
            <div className="pb-5 px-5 text-md text-gray-500">
              Percentage (%)
            </div>
            <div className="flex justify-center h-1/2">
              <GraphH />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
